Feature/41 notify inflate
Meetiing/MeetiingClone pull request #49
Opened 2022-12-12 15:10 UTC by KkamSonLee

## 🎸 작업한 내용
- 앱바 헤더 만들었습니다.
- 더 미뤄지기 전에 넣으려 합니당
- 알림 있을 때 이미지 분기는 서버 없어서 임의로 넣었습니다.
- 알림창 연결 했습니다.
- 알림 Read 여부 시각화
- 알림 클릭 시 result 반환 -> Home Activity에서 분기 처리해야할듯

## 🎶 PR Point

- 알림 클릭 시 어떻게 분기 할 지 고민입니당.

## 📸 스크린샷

https://user-images.githubusercontent.com/15981307/207080745-006493e3-db39-4b58-baf5-bf68ad4c08c9.mov

## 💽 관련 이슈
- Resolved: #41

2022-12-12 15:57 UTC, IslandofDream approved these changes
좋네유 고생많았습니다

2022-12-12 15:57 UTC, IslandofDream commented on app/src/main/java/com/startup/meetiing/presentation/home/HomeActivity.kt
> +                    }*/
알람 이후 플로우때문에 추가된건가?

2022-12-12 15:57 UTC, IslandofDream commented on app/src/main/java/com/startup/meetiing/presentation/notify/NotifyViewModel.kt
> +            _notifySuggestionInfoList.value.map { it.apply { it.isRead = !it.isRead } }
이후 서버통신

2022-12-12 15:57 UTC, IslandofDream commented on app/src/main/java/com/startup/meetiing/presentation/notify/tab/AddGroupFragment.kt
> +    ): View = FragmentNofityTabPageBinding.inflate(inflater, container, false).run {
여기랑 SuggestionInfoFragment는 BindingFragment 사용을 안하던대 NotifyActivity에서 tablayout에 사용하기 위함인거 같은데 따로 안되는 이유가 있나요?

2022-12-12 15:57 UTC, IslandofDream commented on app/src/main/java/com/startup/meetiing/presentation/util/ext/ViewExtension.kt
> +fun TabLayout.changeTabsFont(selectPosition: Int) {
👍

2022-12-12 16:29 UTC, KkamSonLee commented on app/src/main/java/com/startup/meetiing/presentation/home/HomeActivity.kt
> +                    }*/
알림에서 특정 알림을 클릭 했을 때 result를 받아야합니다! 근데 activity간의 전환이라 이 부분에서 NotifyActivity의 Intent Extra 값이 넘어오게 될 것입니다!!

2022-12-12 16:30 UTC, KkamSonLee commented on app/src/main/java/com/startup/meetiing/presentation/notify/tab/AddGroupFragment.kt
> +    ): View = FragmentNofityTabPageBinding.inflate(inflater, container, false).run {
AutoClearedValue 사용해서 그렇습니다!

2022-12-13 10:58 UTC, KkamSonLee commented on app/src/main/java/com/startup/meetiing/presentation/notify/tab/AddGroupFragment.kt
> +    ): View = FragmentNofityTabPageBinding.inflate(inflater, container, false).run {
해당 링크와 같은 이유입니다!
BaseFragment와 거의 동일하긴 합니당!! 까먹지 않으려고 쓰는편!
https://cliearl.github.io/posts/android/prevent-fragment-memory-leak-during-viewbinding/

2022-12-14 13:30 UTC, DAEHYEONJO requested changes
리뷰했습니당

2022-12-14 13:30 UTC, DAEHYEONJO commented on app/src/main/java/com/startup/meetiing/presentation/notify/NotifyActivity.kt
> +        }
Intent수신액티비티(HomeActivity) 에서 companion object로 자기 액티비티 인텐트 만드는 함수 공통적으로 써도 괜찮을듯 (그냥이렇게 통일시키면 어떤가? 하는 의견임이건)

2022-12-14 13:30 UTC, DAEHYEONJO commented on app/src/main/java/com/startup/meetiing/presentation/notify/NotifyListAdapter.kt
> +    private lateinit var inflater: LayoutInflater
그냥궁금한데 이걸 변수로 뺀 이유가 있슴??혹시?

2022-12-14 13:30 UTC, DAEHYEONJO commented on app/src/main/java/com/startup/meetiing/presentation/util/BindingConversion.kt
> +    }
이거 타입 그냥 임시로 string으로 받은건가?

2022-12-14 13:30 UTC, DAEHYEONJO commented on app/src/main/java/com/startup/meetiing/presentation/util/ext/ViewExtension.kt
> +            }
먼가 우리끼리 사용해도 else구문 넣어서 커스텀 익셉션 throw해주는것도 나쁘지 않을듯 머가 문제인지 알수있게 나중에

2022-12-15 11:49 UTC, KkamSonLee commented on app/src/main/java/com/startup/meetiing/presentation/notify/NotifyListAdapter.kt
> +    private lateinit var inflater: LayoutInflater
ItemNotifyListBinding.inflate(inflater, parent, false)를 위한 inflater가 viewHolder가 필요할 때마다 LayoutInflater 객체를 새로 만들어주는 동작을 합니다!! 해당 동작을 위한 LayoutInflater는 1개 뿐이므로 (ViewHolder가 하나니깐) 해당 방법을 통해서 반복 객체 생성을 제한하기 위함입니다!! Lazy 키워드 사용으로 위임하는 방법으로도 가능하긴합니다!

2022-12-15 11:50 UTC, KkamSonLee commented on app/src/main/java/com/startup/meetiing/presentation/util/BindingConversion.kt
> +    }
임시 맞습니다!! 저 당시에 어떻게 넘어오는지 몰라서입니다! 지금은 명시적으로 알 수 있게 String으로 했습니다!

2022-12-15 11:50 UTC, KkamSonLee commented on app/src/main/java/com/startup/meetiing/presentation/util/ext/ViewExtension.kt
> +            }
커스텀 exception 좋습니다 !!

2022-12-15 11:51 UTC, KkamSonLee commented on app/src/main/java/com/startup/meetiing/presentation/notify/NotifyActivity.kt
> +        }
나쁘지않습니당 월요일에 이야기해보죵

2022-12-19 14:10 UTC, merged